@HostAddress = http://localhost:5171
@personId = 984c0d7a-a724-4ef5-84e3-8b8b00e00883

### Get all persons
GET {{HostAddress}}/api/people
Accept: application/json

### Get person by id
GET {{HostAddress}}/api/people/{{personId}}
Accept: application/json

### Create person
POST {{HostAddress}}/api/people
Content-Type: application/json
Accept: application/json

{
  "firstName": "Vanesa",
  "lastName": "Ortiz",
  "email": "vanesa.ortiz@gmail.com",
  "age": 30
}

### Update person
PUT {{HostAddress}}/api/people/7664cb8b-0674-4e7f-97cd-d08f34fecf6e
Content-Type: application/json
Accept: application/json

{
  "firstName": "Vanesa Katherine",
  "lastName": "Ortiz B",
  "email": "vanesa.ortiz@gmail.com",
  "age": 30
}

### Delete person by id
DELETE {{HostAddress}}/api/people/{{personId}}

###
